import type { AgentToolSchema } from '../tool-schema';
import { MINIMAX_LANGUAGE_BOOSTS } from '../../../shared/media-provider-params';

/** Anthropic schema for generating class tools. Just push into this array (it will automatically enter the model's visible tool list). */
export const GENERATE_TOOL_SCHEMAS: AgentToolSchema[] = [
  {
    name: 'submit_image',
    description: 'Generate one or more AI images (gpt-image-2, nano-banana, MiniMax image-01, WaveSpeed, BytePlus Seedream, or xAI Grok Imagine), save them to the project media pool, and optionally propose adding them to the active timeline. Call only when the user explicitly requested the generation.',
    input_schema: {
      type: 'object',
      properties: {
        model: { type: 'string', enum: ['gpt-image-2', 'nano-banana', 'image-01', 'wavespeed', 'byteplus', 'grok-imagine'], description: 'gpt-image-2 is the default; nano-banana is best for reference-heavy work; image-01 is MiniMax (at most 9 outputs; one subject reference when R2 is configured); wavespeed is WaveSpeed AI (fast generic image models, no references); byteplus is BytePlus ModelArk Seedream (no references yet); grok-imagine is xAI Grok Imagine (text-to-image only, no references, at most 4 outputs, 1K/2K).' },
        prompt: { type: 'string', description: 'Detailed description of the image to generate.' },
        name: { type: 'string', description: 'Short descriptive asset name shown in the media pool.' },
        addToTimeline: { type: 'boolean', description: 'Defaults to true. Set false when the user asks to keep the result in the media pool/library only or says not to modify the timeline.' },
        aspectRatio: { type: 'string', enum: ['1:1', '16:9', '9:16', '4:3', '3:4', '3:2', '2:3', '4:5', '5:4', '21:9'], description: 'Defaults to 16:9. Do not send width/height with aspectRatio.' },
        imageSize: { type: 'string', enum: ['512px', '1K', '2K', '4K'], description: 'Defaults to 1K. 512px is Gemini-only; use 2K/4K only when explicitly requested. Ignored when custom width/height are set.' },
        width: { type: 'integer', minimum: 512, maximum: 3840, description: 'Send only when the user explicitly requests custom pixel dimensions. Requires height and omission of aspectRatio. MiniMax max 2048.' },
        height: { type: 'integer', minimum: 512, maximum: 3840, description: 'Send only when the user explicitly requests custom pixel dimensions. Requires width and omission of aspectRatio. MiniMax max 2048.' },
        quality: { type: 'string', enum: ['low', 'medium', 'high', 'auto'], description: 'gpt-image-2 only; defaults to high.' },
        referenceAssetIds: { type: 'array', items: { type: 'string' }, maxItems: 16, description: 'Project image asset IDs. Limits: GPT 16, Gemini 14, MiniMax 1 subject reference (MiniMax needs configured R2).' },
        maskAssetId: { type: 'string', description: 'gpt-image-2 edits only. Project image mask; transparent pixels are replaced.' },
        count: { type: 'integer', minimum: 1, maximum: 10, description: 'Number of images; defaults to 1. image-01 max 9.' },
        background: { type: 'string', enum: ['transparent', 'opaque', 'auto'], description: 'gpt-image-2 only. Output background.' },
        moderation: { type: 'string', enum: ['low', 'auto'], description: 'gpt-image-2 only. Moderation strictness.' },
        inputFidelity: { type: 'string', enum: ['low', 'high'], description: 'gpt-image-2 edits only. Reference-image fidelity.' },
        outputFormat: { type: 'string', enum: ['png', 'jpeg', 'webp'], description: 'gpt-image-2 only. Defaults to png.' },
        outputCompression: { type: 'integer', minimum: 0, maximum: 100, description: 'gpt-image-2 only. Send only with outputFormat=jpeg or webp; never send for PNG.' },
        seed: { type: 'integer', description: 'MiniMax image-01 only. Reproducible random seed.' },
        promptOptimizer: { type: 'boolean', description: 'MiniMax image-01 only. prompt_optimizer; official default false.' },
      },
      required: ['prompt', 'name'],
    },
  },
  {
    name: 'submit_voice',
    description: 'Generate one TTS audio asset with ElevenLabs, Doubao, MiniMax, Inworld, Fish Audio, Speechify, OpenAI, Gemini, Mistral, or Cartesia. Creates a media-pool asset only; it does not place or replace timeline items. Confirm a configured provider and concrete provider-specific voice; MiniMax timbreWeights may mix voices with an empty voiceId.',
    input_schema: {
      type: 'object',
      properties: {
        provider: { type: 'string', enum: ['elevenlabs', 'doubao', 'minimax', 'inworld', 'fishaudio', 'speechify', 'openai', 'gemini', 'mistral', 'cartesia'], description: 'Required opt-in provider. Use only a provider listed as configured in capabilities. Voice IDs and catalogs are never interchangeable.' },
        text: { type: 'string', minLength: 1, description: 'Text to synthesize.' },
        voiceId: { type: 'string', description: 'Concrete provider-specific voice ID confirmed by the user. Required except MiniMax timbreWeights mixing, where it must be empty. Do not invent a preset or reuse an ID from another provider.' },
        modelId: { type: 'string', description: 'ElevenLabs, Inworld, Fish Audio, Speechify, OpenAI, Gemini, Mistral, or Cartesia only. Omit to use the configured model.' },
        stability: { type: 'number', minimum: 0, maximum: 1, description: 'ElevenLabs only. Defaults to 0.5.' },
        speed: { type: 'number', minimum: 0.5, maximum: 2, description: 'ElevenLabs (0.7–1.2), MiniMax (0.5–2), OpenAI, or Cartesia only. Defaults to 1; provider/model support is validated server-side.' },
        similarityBoost: { type: 'number', minimum: 0, maximum: 1, description: 'ElevenLabs voice_settings.similarity_boost.' },
        style: { type: 'number', minimum: 0, maximum: 1, description: 'ElevenLabs voice_settings.style.' },
        useSpeakerBoost: { type: 'boolean', description: 'ElevenLabs speaker boost.' },
        languageCode: { type: 'string', description: 'ElevenLabs or Cartesia only. Provider/model support is validated server-side.' },
        seed: { type: 'integer', minimum: 0, maximum: 4294967295, description: 'ElevenLabs reproducibility seed.' },
        outputFormat: { type: 'string', description: 'ElevenLabs official output enum (for example mp3_44100_128) or OpenAI/Gemini/Mistral/Cartesia provider-supported output format.' },
        instructions: { type: 'string', description: 'OpenAI or Gemini only. Optional natural-language delivery instructions; send only when requested and supported by the configured model.' },
        optimizeStreamingLatency: { type: 'integer', minimum: 0, maximum: 4, description: 'ElevenLabs latency optimization level.' },
        enableLogging: { type: 'boolean', description: 'ElevenLabs request logging query control.' },
        applyTextNormalization: { type: 'string', enum: ['auto', 'on', 'off'], description: 'ElevenLabs text normalization.' },
        applyLanguageTextNormalization: { type: 'boolean', description: 'ElevenLabs language text normalization.' },
        pronunciationDictionaryLocators: { type: 'array', maxItems: 3, items: { type: 'object', properties: { pronunciationDictionaryId: { type: 'string' }, versionId: { type: 'string' } }, required: ['pronunciationDictionaryId', 'versionId'] }, description: 'ElevenLabs dictionary/version locators.' },
        previousText: { type: 'string', description: 'ElevenLabs continuity context before this text.' },
        nextText: { type: 'string', description: 'ElevenLabs continuity context after this text.' },
        previousRequestIds: { type: 'array', items: { type: 'string' }, description: 'ElevenLabs prior request IDs for continuity.' },
        nextRequestIds: { type: 'array', items: { type: 'string' }, description: 'ElevenLabs next request IDs for continuity.' },
        speedRatio: { type: 'number', minimum: 0.5, maximum: 2, description: 'Doubao only. Defaults to 1.' },
        emotion: { type: 'string', description: 'Doubao or MiniMax emotion label. MiniMax accepts: happy, sad, angry, fearful, disgusted, surprised, calm, fluent, whisper.' }, // minimax: shared with doubao
        emotionScale: { type: 'number', minimum: 1, maximum: 5, description: 'Doubao only. Requires emotion.' },
        loudnessRatio: { type: 'number', minimum: 0.5, maximum: 2, description: 'Doubao only. Defaults to 1.' },
        pitch: { type: 'number', minimum: -12, maximum: 12, description: 'Doubao: post-process semitones. MiniMax: native voice_setting.pitch (-12–12).' },
        volume: { type: 'number', exclusiveMinimum: 0, maximum: 10, description: 'MiniMax only. voice_setting.vol (>0–10). Defaults to 1.' },
        performancePrompt: { type: 'string', maxLength: 200, description: 'Doubao only. Natural-language performance direction.' },
        explicitDialect: { type: 'string', enum: ['dongbei', 'shaanxi', 'sichuan'], description: 'Doubao only; supported by the Vivi preset.' },
        // ponytail: Numeric enum will be rejected by Gemini native API (Schema.enum only accepts TYPE_STRING) - write in
        // description, the provider API side will still verify illegal values.
        sampleRate: { type: 'integer', description: 'MiniMax audio_setting.sample_rate. One of 8000/16000/22050/24000/32000/44100.' },
        bitrate: { type: 'integer', description: 'MiniMax MP3 bitrate. One of 32000/64000/128000/256000.' },
        audioFormat: { type: 'string', enum: ['mp3', 'pcm', 'flac', 'wav', 'pcmu_raw', 'pcmu_wav', 'opus'], description: 'MiniMax audio output format.' },
        channel: { type: 'integer', minimum: 1, maximum: 2, description: 'MiniMax output channels (1 = mono, 2 = stereo).' },
        forceCbr: { type: 'boolean', description: 'MiniMax constant bitrate; true requires stream=true and MP3.' },
        stream: { type: 'boolean', description: 'MiniMax HTTP streaming transport. Aquarius Cut consumes it server-side and saves one durable audio asset.' },
        excludeAggregatedAudio: { type: 'boolean', description: 'MiniMax stream option. Requires stream=true; concatenates incremental chunks.' },
        languageBoost: { type: 'string', enum: [...MINIMAX_LANGUAGE_BOOSTS], description: 'MiniMax official language_boost enum.' },
        textNormalization: { type: 'boolean', description: 'MiniMax text_normalization.' },
        latexRead: { type: 'boolean', description: 'MiniMax latex_read.' },
        pronunciations: { type: 'array', items: { type: 'string' }, description: 'MiniMax pronunciation_dict.tone entries.' },
        timbreWeights: { type: 'array', minItems: 1, maxItems: 4, items: { type: 'object', properties: { voiceId: { type: 'string' }, weight: { type: 'integer', minimum: 1, maximum: 100 } }, required: ['voiceId', 'weight'] }, description: 'MiniMax multi-voice timbre mix.' },
        voiceModify: { type: 'object', properties: { pitch: { type: 'number', minimum: -100, maximum: 100 }, intensity: { type: 'number', minimum: -100, maximum: 100 }, timbre: { type: 'number', minimum: -100, maximum: 100 }, effect: { type: 'string', enum: ['spacious_echo', 'auditorium_echo', 'lofi_telephone', 'robotic'] } }, description: 'MiniMax voice_modify controls.' },
        subtitleEnable: { type: 'boolean', description: 'MiniMax subtitle generation flag; the JSON response is downloaded as a durable sidecar.' },
        subtitleType: { type: 'string', enum: ['sentence', 'word', 'word_streaming'], description: 'MiniMax subtitle granularity. Requires subtitleEnable; word_streaming also requires stream.' },
        name: { type: 'string', description: 'Optional media-pool asset name.' },
      },
      required: ['provider', 'text'],
    },
  },
  {
    name: 'submit_sound',
    description: 'Generate one sound-effect audio asset in the media pool: ElevenLabs synthesizes synchronously from a text prompt; Sonilo submits an asynchronous SFX job from a project video asset (the rendered cut, up to 3 minutes) with no prompt. Sonilo returns a jobId for track_progress. Does not place timeline items. For ordinary whooshes, clicks, impacts, dings, and similar editing sounds, use the existing library first.',
    input_schema: {
      type: 'object',
      properties: {
        provider: { type: 'string', enum: ['elevenlabs', 'sonilo'], description: 'Defaults to elevenlabs (text prompt). sonilo generates video-matched SFX from sourceAssetId instead of a prompt.' },
        prompt: { type: 'string', description: 'Detailed sound description. Required for elevenlabs; not used by sonilo.' },
        durationSeconds: { type: 'number', minimum: 0.5, maximum: 30, description: 'ElevenLabs only. Optional 0.5–30 seconds; omit to let ElevenLabs choose the duration.' },
        promptInfluence: { type: 'number', minimum: 0, maximum: 1, description: 'ElevenLabs only. Prompt adherence; defaults to 0.3.' },
        loop: { type: 'boolean', description: 'ElevenLabs only. Create a seamless loop; requires the configured eleven_text_to_sound_v2 model.' },
        outputFormat: { type: 'string', description: 'ElevenLabs only. Official codec_sample-rate_bitrate enum, e.g. mp3_44100_128, opus_48000_128, pcm_44100.' },
        sourceAssetId: { type: 'string', description: 'Sonilo only. Project video asset (the rendered cut, ≤3 minutes) the SFX are generated from.' },
        name: { type: 'string', description: 'Optional media-pool asset name.' },
      },
    },
  },
  {
    name: 'submit_music',
    description: 'Submit a Mureka, MiniMax, Atlas Cloud, or Sonilo music job. Mureka supports instrumental, lyrics song, prompt song, soundtrack, and track/stem modes with up to 3 results. MiniMax supports text-to-music and cover. Atlas Cloud supports text-to-music through its asynchronous audio API. Sonilo v2m generates music from a project video asset (the rendered cut, up to 6 minutes) — video-conditioned, with a single optional style prompt. Results are saved to the media pool.',
    input_schema: {
      type: 'object',
      properties: {
        prompt: { type: 'string', maxLength: 2000, description: 'Style/control prompt. Required for most modes; optional with Mureka provider IDs and Sonilo v2m (≤500, works promptless). Mureka max is 1024 or 2000 by mode; MiniMax cover requires 10–300.' },
        provider: { type: 'string', enum: ['mureka', 'minimax', 'atlas', 'sonilo'], description: 'Defaults to mureka.' },
        mode: { type: 'string', enum: ['instrumental', 'song', 'prompt-song', 'soundtrack', 'track', 't2m', 'cover', 'v2m'], description: 'Mureka: instrumental/song/prompt-song/soundtrack/track. MiniMax: t2m/cover. Atlas Cloud: t2m. Sonilo: v2m (video-to-music).' },
        lyrics: { type: 'string', maxLength: 5000, description: 'Mureka song/track or MiniMax t2m/cover lyrics. Provider-specific limits are validated.' },
        isInstrumental: { type: 'boolean', description: 'MiniMax or Atlas Cloud t2m only. Force instrumental.' },
        lyricsOptimizer: { type: 'boolean', description: 'MiniMax t2m only. Auto-generate lyrics from prompt.' },
        sampleRate: { type: 'integer', description: 'MiniMax or Atlas Cloud only. One of 16000/24000/32000/44100; default 44100.' },
        bitrate: { type: 'integer', description: 'MiniMax or Atlas Cloud only. One of 32000/64000/128000/256000; default 256000.' },
        audioFormat: { type: 'string', enum: ['mp3', 'wav', 'pcm', 'flac'], description: 'MiniMax/Atlas Cloud: mp3/wav/pcm. Mureka: mp3/wav/flac. Default mp3.' },
        referenceAssetId: { type: 'string', description: 'MiniMax cover only. Project audio asset id; mutually exclusive with coverFeatureId.' },
        coverFeatureId: { type: 'string', description: 'MiniMax cover only. Preprocessed feature ID; requires lyrics and excludes referenceAssetId.' },
        count: { type: 'integer', minimum: 1, maximum: 3, description: 'Mureka only. Result count; defaults to 1 (official API default is 2).' },
        stream: { type: 'boolean', description: 'Mureka only. Enable provider streaming phase; Aquarius Cut still saves durable final files.' },
        styles: { type: 'array', items: { type: 'string', enum: ['pop', 'rock', 'jazz', 'r&b', 'edm', 'ambient', 'folk', 'latin', 'k-pop', 'j-pop', 'house', 'gospel', 'lo-fi'] }, description: 'Mureka prompt-song styles.' },
        gender: { type: 'string', enum: ['female', 'male'], description: 'Mureka lyrics-song preferred vocal gender.' },
        referenceId: { type: 'string', description: 'Mureka song/prompt-song reference ID.' },
        instrumentalId: { type: 'string', description: 'Mureka instrumental file ID; use instead of prompt.' },
        vocalId: { type: 'string', description: 'Mureka cloned vocal ID.' },
        melodyId: { type: 'string', description: 'Mureka lyrics-song melody ID; cannot combine with other controls.' },
        sourceAssetId: { type: 'string', description: 'Mureka soundtrack image/video asset, track-mode audio asset, or Sonilo v2m video asset (the rendered cut, ≤6 minutes).' },
        audioStartMs: { type: 'integer', minimum: 0, description: 'Mureka soundtrack segment start in ms.' },
        audioEndMs: { type: 'integer', minimum: 0, description: 'Mureka soundtrack segment end in ms; range must be at least 3000ms.' },
        songId: { type: 'string', description: 'Mureka track source song ID; excludes sourceAssetId.' },
        trackType: { type: 'string', enum: ['Vocals', 'Instrumental', 'Drums', 'Bass', 'Guitar', 'Keyboard', 'Percussion', 'Strings', 'Synth', 'FX', 'Brass', 'Woodwinds'], description: 'Mureka track/stem type.' },
        generateStartMs: { type: 'integer', minimum: 0, description: 'Mureka track source segment start in ms.' },
        generateEndMs: { type: 'integer', minimum: 0, description: 'Mureka track source segment end in ms.' },
        vocalGender: { type: 'string', enum: ['female', 'male'], description: 'Mureka Vocals track only.' },
        name: { type: 'string', description: 'Optional media-pool asset name.' },
      },
    },
  },
  {
    name: 'submit_video',
    description: 'Submit a Seedance 2.0, Kling, MiniMax Hailuo, BytePlus Seedance, or xAI Grok Imagine video generation job and create one video asset in the project media pool. Does not place the video on the timeline. Keep image, video, and audio references in their matching arrays.',
    input_schema: {
      type: 'object',
      properties: {
        model: { type: 'string', enum: ['seedance2', 'kling', 'hailuo', 'byteplus', 'grok-imagine-video'], description: 'hailuo is MiniMax: 6 or 10s; firstFrame optional; lastFrame allowed with firstFrame; no multi-ref or multi-shot. 1080p is 6s only. byteplus is BytePlus ModelArk Seedance — same request shape/limits as seedance2. grok-imagine-video is xAI Grok Imagine: text-to-video only, 1–15s, audio track included, no references/frames.' }, // minimax: hailuo enum
        prompt: { type: 'string', description: 'Required for normal generation and Kling intelligence; omit for Kling customize.' },
        name: { type: 'string' },
        durationSeconds: { anyOf: [{ type: 'number' }, { type: 'string' }], description: 'Integer seconds, 2–15 for Seedance, 3–15 for Kling, exactly 6 or 10 for Hailuo (Hailuo 1080p → 6 only), 1–15 for grok-imagine-video.' }, // minimax: hailuo durations
        ratio: { type: 'string', description: 'Seedance: 16:9, 4:3, 1:1, 3:4, 9:16, 21:9, adaptive. Kling: 16:9, 9:16, 1:1. grok-imagine-video: 16:9, 9:16, 1:1, 4:3, 3:4, 3:2, 2:3. Do not send for hailuo.' },
        resolution: { type: 'string', enum: ['480p', '512p', '720p', '1080p', '4k'], description: 'Seedance: 480p/720p(default)/1080p/4k. Hailuo: 512p (Hailuo-02), 720p→API 768P, 1080p (6s only). Kling: pair with mode std/pro. grok-imagine-video: 480p(default)/720p/1080p.' },
        mode: { type: 'string', enum: ['std', 'pro'], description: 'Kling only; std=720p, pro=1080p.' },
        firstFrame: { type: 'string', description: 'Project image asset ID, asset:// ID, short unique ID prefix, or same-project asset path.' },
        lastFrame: { type: 'string', description: 'Project image asset reference; requires firstFrame. Supported on seedance2, kling, and hailuo (not with multi-ref on seedance2).' },
        refImages: { type: 'array', items: { type: 'string' } },
        refVideos: { type: 'array', items: { type: 'string' } },
        refAudios: { type: 'array', items: { type: 'string' } },
        refVideoMode: { type: 'string', enum: ['feature', 'base'], description: 'Kling only with refVideos. feature (default)=motion/camera/style guide; base=edit that source clip (keep_original_sound).' },
        promptOptimizer: { type: 'boolean', description: 'Hailuo only. MiniMax prompt_optimizer; default true. Set false for more literal prompts.' },
        fastPretreatment: { type: 'boolean', description: 'Hailuo only. MiniMax fast_pretreatment when promptOptimizer is true; default false.' },
        generateAudio: { type: 'boolean', description: 'Seedance/BytePlus only. Generate synchronized audio; official default true.' },
        seed: { type: 'integer', description: 'Seedance/BytePlus only. Deterministic random seed.' },
        cameraFixed: { type: 'boolean', description: 'Seedance/BytePlus only. Lock camera motion; default false.' },
        watermark: { type: 'boolean', description: 'Seedance/BytePlus only. Add provider watermark; default false.' },
        returnLastFrame: { type: 'boolean', description: 'Seedance/BytePlus only. Save the returned last frame as an additional image asset.' },
        executionExpiresAfter: { type: 'integer', minimum: 3600, maximum: 259200, description: 'Seedance/BytePlus only. Task expiry in seconds.' },
        priority: { type: 'integer', minimum: 0, maximum: 9, description: 'Seedance/BytePlus only. Queue priority.' },
        multiPrompts: {
          type: 'array', minItems: 2, maxItems: 6,
          items: { type: 'object', properties: { prompt: { type: 'string' }, duration: { anyOf: [{ type: 'number' }, { type: 'string' }] }, index: { type: 'integer', minimum: 1 } }, required: ['prompt', 'duration', 'index'] },
          description: 'Kling customize storyboard; indexes start at 1 and durations sum to durationSeconds.',
        },
        shotType: { type: 'string', enum: ['customize', 'intelligence'], description: 'Kling multi-shot mode.' },
      },
      required: ['model'],
    },
  },
  {
    name: 'track_progress',
    description: 'Inspect or wait for asynchronous generation jobs returned by Sonilo submit_sound, submit_music, and submit_video. Successful results are added to the project media pool exactly once.',
    input_schema: {
      type: 'object',
      properties: {
        action: { type: 'string', enum: ['params', 'status', 'wait', 'resume'], description: 'params returns settings, status checks immediately, wait polls, and resume retries only a failed result download without regenerating.' },
        target: { type: 'string', enum: ['generation'] },
        jobIds: { type: 'string', minLength: 1, description: 'One or more comma-separated generation job IDs.' },
        assetIds: { type: 'string', description: 'Reserved; generation jobs are tracked by jobIds.' },
        timeoutSeconds: { type: 'number', minimum: 0, maximum: 3600, description: 'wait timeout; defaults to 90 seconds.' },
      },
      required: ['action', 'target', 'jobIds'],
    },
  },
  {
    name: 'rerun_generation',
    description: 'Explicitly rerun one previously tracked generation operation with its complete original submit args. Exact operation/job IDs win; a prefix is accepted only when unique. Legacy summary-only rows and ambiguous prefixes are rejected before any provider call.',
    input_schema: {
      type: 'object',
      properties: {
        jobId: { type: 'string', minLength: 1, description: 'Exact operation/job ID or a unique prefix. Ambiguous prefixes are rejected with distinguishable candidate IDs.' },
      },
      required: ['jobId'],
    },
  },
  {
    name: 'submit_export',
    description: [
      'Export the active timeline synchronously as MP4/WebM video, MP3/WAV audio, SRT/TXT subtitles,',
      'or an FCPXML project (format=xml) for Premiere / Resolve / FCP.',
      'When MG/captions reference fonts the renderer cannot load, the first call returns unsupportedFonts',
      '— relay to the user and retry with confirmFontFallback=true only after they accept.',
      'For XML, pass nleFormat=fcp_xml (default, Premiere) or fcp_xml_resolve (DaVinci Resolve).',
      'Optional frame boundaries use a half-open [startFrame, endFrameExclusive) range.',
    ].join(' '),
    input_schema: {
      type: 'object',
      properties: {
        format: { type: 'string', enum: ['video', 'audio', 'subtitles', 'xml'] },
        codec: { type: 'string', enum: ['h264', 'vp8', 'mp3', 'wav'], description: 'Video: h264 (default) or vp8. Audio: mp3 (default) or wav.' },
        subtitleFormat: { type: 'string', enum: ['srt', 'txt'], description: 'Defaults to srt.' },
        captionTrackId: { type: 'string', description: 'For subtitle export: C1/C2 alias or stable caption track id. Defaults to C1.' },
        nleFormat: {
          type: 'string',
          enum: ['fcp_xml', 'fcp_xml_resolve'],
          description: 'NLE XML format for format=xml. Defaults to fcp_xml (Premiere). Use fcp_xml_resolve for DaVinci Resolve.',
        },
        name: { type: 'string', description: 'Download filename.' },
        fps: {
          type: 'number',
          description: 'Video output fps: 24|25|30|50|60. Omit to match timeline. Frame counts stay; real duration scales.',
        },
        resolution: {
          type: 'string',
          enum: ['480p', '720p', '1080p'],
          description: 'Video max-height ladder (default timeline size). Scales width to keep aspect.',
        },
        videoBitrate: {
          type: 'integer',
          minimum: 1_000_000,
          maximum: 80_000_000,
          description: 'Video only. Exact output bitrate in bits per second; omit for the renderer default.',
        },
        timelineId: {
          type: 'string',
          description: 'Export a non-active timeline by id/prefix without switching (video/audio/xml).',
        },
        startFrame: { type: 'integer', minimum: 0 },
        endFrameExclusive: { type: 'integer', minimum: 1 },
        startSeconds: { type: 'number', minimum: 0, description: 'Legacy; prefer startFrame.' },
        endSeconds: { type: 'number', minimum: 0, description: 'Legacy; prefer endFrameExclusive.' },
        confirmFontFallback: {
          type: 'boolean',
          description: 'Required true when export would burn unsupported fonts. First call without it returns the unsupported list.',
        },
        motionGraphicRenderKeys: {
          type: 'array',
          items: { type: 'string' },
          description: 'Advanced XML export: render keys returned by export_motion_graphic_prores with filenameMode=xml. Matching MG clips become media references; other MG clips stay placeholders.',
        },
      },
    },
  },
];

export const GENERATE_TOOL_NAMES = new Set(GENERATE_TOOL_SCHEMAS.map((tool) => tool.name));
