// ZH dictionary shard (key = English source string, value = Chinese).
// Generated by inverting the original Chinese-keyed EN dictionary when English became
// the source language of this fork. Add new entries here when new English UI copy lands.
export default {
  'Push & Pull Back': '推进拉回',
  'Slow Push': '慢推',
  'Zoom Out': '拉远',
  'Ease-In Push': '缓入推近',
  'Bouncy Push': '弹性推近',
  'Snap Push': '快切推近',
  'Whip-In Push': '甩入推近',
  'Anticipation Zoom': '推进转场',
  'Clean Line Wipe': '白色划线转场',
  'Cross Dissolve': '叠化转场',
  'Dip to Black': '闪黑转场',
  'Impact Shake': '冲击抖动转场',
  'Luma Blend': '叠加转场',
  'Organic Dissolve': '光溶转场',
  'Page Curl': '翻页转场',
  'Rack Focus': '焦点转场',
  'Soft Wipe': '柔化擦除转场',
  'Whip Pan': '甩镜转场',
  'Circle Wipe': '圆形擦除转场',
  'Voice isolation failed; no clips were modified.': '人声分离失败，未修改任何片段。',
  'Loudness analysis failed; no clips were modified.': '响度分析失败，未修改任何片段。',
  'Source media changed; the previous voice separation result was discarded. Retry.': '所选片段的源素材已变化，旧的人声分离结果已丢弃。请重试。',
} as Record<string, string>;
