// ZH dictionary shard (key = English source string, value = Chinese).
// Generated by inverting the original Chinese-keyed EN dictionary when English became
// the source language of this fork. Add new entries here when new English UI copy lands.
export default {
} as Record<string, string>;
