// ZH dictionary shard (key = English source string, value = Chinese).
// Generated by inverting the original Chinese-keyed EN dictionary when English became
// the source language of this fork. Add new entries here when new English UI copy lands.
export default {
  'Review comments': '审阅评论',
  'Comments': '评论',
  'Failed to load comments': '评论加载失败',
  'Failed to save comment': '评论保存失败',
  'Failed to save reply': '回复保存失败',
  'Add a review comment at the current frame': '在当前帧添加审阅评论',
  'Anchors to this frame and, when available, the clip and source position': '绑定当前帧；可用时同时记录片段与源位置',
  'Add comment': '添加评论',
  'No review comments yet': '还没有审阅评论',
  'Write a reply': '输入回复',
  'Reply': '回复',
  'Reopen': '重新打开',
  'Resolve': '解决',
  'Delete comment': '删除评论',
} as Record<string, string>;
