// ZH dictionary shard (key = English source string, value = Chinese).
// Generated by inverting the original Chinese-keyed EN dictionary when English became
// the source language of this fork. Add new entries here when new English UI copy lands.
export default {
  'Switch UI language': '切换界面语言',
  'Back to projects': '返回工程列表',
  'Edit keyboard shortcuts': '编辑快捷键',
  'Undo': '撤销',
  'Redo': '重做',
  'Design style (brand)': '设计风格(品牌)',
  'Toggle panel layout': '切换面板布局',
  'Export MP4': '导出 MP4',
  'Account': '账户',
  'Window controls': '窗口控制',
  'Close window': '关闭窗口',
  'Minimize window': '最小化窗口',
  'Maximize window': '最大化窗口',
  'Restore window': '还原窗口',
} as Record<string, string>;
