// Wire protocol between the built-in LLM service (in the server process) and
// the worker that actually holds the llama.cpp model.
//
// Deliberately tiny and structurally validated on both sides, exactly like
// `shared/desktop-inference.ts`: the worker is a separate OS process, so every
// message crossing the boundary is parsed rather than trusted.

export interface BuiltinLlmInitialize {
  readonly type: 'initialize';
  /** Absolute path of the verified GGUF file. */
  readonly modelPath: string;
  readonly contextSize: number;
}

export interface BuiltinLlmMessage {
  readonly role: 'user' | 'assistant';
  readonly content: string;
}

export interface BuiltinLlmGenerateRequest {
  readonly type: 'generate';
  readonly requestId: string;
  readonly system: string;
  readonly messages: readonly BuiltinLlmMessage[];
  readonly maxTokens: number;
  readonly temperature: number;
}

export type BuiltinLlmRequest = BuiltinLlmInitialize | BuiltinLlmGenerateRequest;

export interface BuiltinLlmReady {
  readonly type: 'ready';
  /** Which llama.cpp backend the worker got — 'metal', 'cuda', 'vulkan', 'cpu'… */
  readonly gpu: string;
  readonly loadMs: number;
}

export interface BuiltinLlmResult {
  readonly type: 'result';
  readonly requestId: string;
  readonly text: string;
  readonly generateMs: number;
}

export interface BuiltinLlmFailure {
  readonly type: 'error';
  /** Absent for a load failure, which fails every queued request. */
  readonly requestId?: string;
  readonly message: string;
}

export type BuiltinLlmResponse = BuiltinLlmReady | BuiltinLlmResult | BuiltinLlmFailure;

/** Request ids are generated by the service; keep them boring and bounded. */
export function isBuiltinLlmRequestId(value: unknown): value is string {
  return typeof value === 'string' && /^[A-Za-z0-9_-]{1,64}$/.test(value);
}

function record(value: unknown): Record<string, unknown> | null {
  return typeof value === 'object' && value !== null && !Array.isArray(value)
    ? value as Record<string, unknown>
    : null;
}

export function parseBuiltinLlmResponse(value: unknown): BuiltinLlmResponse | null {
  const message = record(value);
  if (!message) return null;
  if (message.type === 'ready') {
    return typeof message.gpu === 'string' && typeof message.loadMs === 'number'
      ? { type: 'ready', gpu: message.gpu, loadMs: message.loadMs }
      : null;
  }
  if (message.type === 'result') {
    return isBuiltinLlmRequestId(message.requestId)
      && typeof message.text === 'string'
      && typeof message.generateMs === 'number'
      ? { type: 'result', requestId: message.requestId, text: message.text, generateMs: message.generateMs }
      : null;
  }
  if (message.type === 'error') {
    if (typeof message.message !== 'string') return null;
    if (message.requestId === undefined) return { type: 'error', message: message.message };
    return isBuiltinLlmRequestId(message.requestId)
      ? { type: 'error', requestId: message.requestId, message: message.message }
      : null;
  }
  return null;
}

export function parseBuiltinLlmRequest(value: unknown): BuiltinLlmRequest | null {
  const message = record(value);
  if (!message) return null;
  if (message.type === 'initialize') {
    return typeof message.modelPath === 'string' && message.modelPath.length > 0
      && typeof message.contextSize === 'number' && message.contextSize > 0
      ? { type: 'initialize', modelPath: message.modelPath, contextSize: Math.round(message.contextSize) }
      : null;
  }
  if (message.type !== 'generate') return null;
  if (!isBuiltinLlmRequestId(message.requestId)) return null;
  if (typeof message.system !== 'string') return null;
  if (!Array.isArray(message.messages)) return null;
  const messages: BuiltinLlmMessage[] = [];
  for (const entry of message.messages) {
    const item = record(entry);
    if (!item || (item.role !== 'user' && item.role !== 'assistant')) return null;
    if (typeof item.content !== 'string') return null;
    messages.push({ role: item.role, content: item.content });
  }
  if (messages.length === 0) return null;
  return {
    type: 'generate',
    requestId: message.requestId,
    system: message.system,
    messages,
    maxTokens: typeof message.maxTokens === 'number' && message.maxTokens > 0 ? Math.round(message.maxTokens) : 1024,
    temperature: typeof message.temperature === 'number' && message.temperature >= 0 ? message.temperature : 0.2,
  };
}

/**
 * Qwen3 and every other hybrid-reasoning model can emit a `<think>` block ahead
 * of its answer. The composition linter would reject that prose outright, so it
 * is stripped before the draft is ever looked at — including the half-open case
 * where generation started mid-thought and only the closing tag survives.
 */
export function stripReasoningBlocks(raw: string): string {
  return String(raw ?? '')
    .replace(/<think>[\s\S]*?<\/think>/gi, '')
    .replace(/^[\s\S]*?<\/think>/i, '')
    .trim();
}
