// OS-managed overlay updates — the AquariusOS path.
//
// On AquariusOS the app is baked into the read-only OS image, extracted (not as an
// AppImage), at /usr/lib/aquarius/aquarius-editor/ and started by a small launcher
// script at /usr/bin/aquarius-editor. Nothing in the image can be written, so the
// normal in-place updaters (NSIS on Windows, AppImageUpdater on Linux) cannot run.
//
// The contract with the OS launcher:
//   - the launcher exports AQUARIUS_OS_MANAGED_INSTALL=1 and AQUARIUS_UPDATE_OVERLAY_DIR
//   - the launcher runs <overlayRoot>/current when that symlink resolves to a newer
//     build than the one in the image, and the image copy otherwise
//   - this module owns everything under <overlayRoot>: it downloads the release's Linux
//     x86_64 AppImage, verifies it against the release's SHA256SUMS.txt, self-extracts it
//     (--appimage-extract needs no FUSE), and atomically repoints `current`
//
// The image copy is never touched, so a failed or half-finished update simply leaves the
// OS-baked version running. Everything here is plain Node — no Electron — so the whole
// flow is exercised by overlay-update.verify.ts against temp directories.
import { spawn } from 'node:child_process';
import { createHash } from 'node:crypto';
import { createReadStream, createWriteStream } from 'node:fs';
import {
  chmod, lstat, mkdir, mkdtemp, readdir, readlink, rename, rm, stat, symlink,
} from 'node:fs/promises';
import { isAbsolute, join } from 'node:path';
import { Readable, Transform } from 'node:stream';
import { pipeline } from 'node:stream/promises';

/** Set to '1' by the AquariusOS launcher when this build lives in the read-only image. */
export const OS_MANAGED_INSTALL_ENV = 'AQUARIUS_OS_MANAGED_INSTALL';
/** Absolute writable directory the launcher hands us for updated copies. */
export const OVERLAY_DIR_ENV = 'AQUARIUS_UPDATE_OVERLAY_DIR';
/** Used when the launcher sets the mode flag but not the directory. */
export const DEFAULT_OVERLAY_DIR = '.local/share/aquarius/aquarius-editor';
/** The OS launcher script. Restarting means going back through it, never through argv[0]. */
export const OS_ENTRY_POINT = '/usr/bin/aquarius-editor';

// Release assets are named by config/electron-builder.config.mjs
// (artifactName 'AquariusEditor-${version}-${arch}.${ext}'); electron-builder spells the
// AppImage architecture x86_64. SHA256SUMS.txt is generated by the release workflow.
// update-packaging.verify.ts pins these three to the packaging config so they cannot drift.
export const RELEASE_DOWNLOAD_BASE = 'https://github.com/stoneharborent/aquarius-editor/releases/download';
export const CHECKSUM_ASSET_NAME = 'SHA256SUMS.txt';

/**
 * GitHub's hard ceiling for a single release asset: "Each file included in a
 * release must be under 2 GiB."
 * https://docs.github.com/en/repositories/releasing-projects-on-github/about-releases
 *
 * This is the limit that made v0.6.0 unshippable — every installer built with
 * the 2.33 GiB HyperFrames GGUF inside it landed at 3.8–4.05 GiB. It is not a
 * guideline we chose and it cannot be raised, so it bounds what may ever be
 * bundled into an installer (see shared/bundled-models.ts).
 *
 * Two places enforce it, and they must agree:
 *   • desktop/bundled-models-catalog.verify.ts — at build-config time, against
 *     the payload the catalogs describe, so an oversized model is caught before
 *     anyone spends 40 minutes packaging it.
 *   • .github/workflows/desktop.yml — on the real files, per platform, right
 *     after Package, so the release job can never reach `gh release upload`
 *     with an asset GitHub will reject.
 */
export const MAX_RELEASE_ASSET_BYTES = 2 * 1024 * 1024 * 1024;

const SEMVER = /^\d+\.\d+\.\d+(?:-[0-9A-Za-z.-]+)?$/;
const CURRENT_LINK = 'current';
const VERSIONS_DIR = 'versions';
const WORK_DIR = 'tmp';
const EXTRACTED_DIR = 'squashfs-root';

export interface OverlayReleaseAssets {
  readonly assetName: string;
  readonly appImageUrl: string;
  readonly checksumsUrl: string;
}

export interface OverlayInstallHooks {
  /** 0–100 while the AppImage is coming down the wire. */
  readonly onProgress?: (percent: number) => void;
  /** Fired once the download is verified and the slow extract/swap begins. */
  readonly onExtractStart?: () => void;
}

export interface OverlayUpdateIo {
  readonly downloadFile: (
    url: string,
    destination: string,
    onProgress: (percent: number) => void,
  ) => Promise<void>;
  readonly fetchText: (url: string) => Promise<string>;
  readonly hashFile: (path: string) => Promise<string>;
  readonly extractAppImage: (appImagePath: string, workDir: string) => Promise<void>;
}

export interface OverlayUpdateInstaller {
  readonly overlayRoot: string;
  readonly install: (version: string, hooks?: OverlayInstallHooks) => Promise<string>;
}

/** True when the AquariusOS launcher started this build out of the read-only image. */
export function isOsManagedInstall(env: NodeJS.ProcessEnv): boolean {
  return env[OS_MANAGED_INSTALL_ENV] === '1';
}

/**
 * The writable overlay root, or null when this is not an OS-managed install.
 *
 * A relative AQUARIUS_UPDATE_OVERLAY_DIR is ignored rather than resolved against an
 * arbitrary working directory: the launcher always passes an absolute path, so anything
 * else is a mistake and the documented default is the safer answer.
 */
export function resolveOverlayRoot(env: NodeJS.ProcessEnv): string | null {
  if (!isOsManagedInstall(env)) return null;
  const configured = env[OVERLAY_DIR_ENV]?.trim();
  if (configured && isAbsolute(configured)) return configured;
  const home = env.HOME?.trim();
  if (!home || !isAbsolute(home)) return null;
  return join(home, DEFAULT_OVERLAY_DIR);
}

/** Rejects anything that is not a bare semver, so a version can never escape its directory. */
export function normalizeOverlayVersion(version: string): string {
  const normalized = version.trim().replace(/^v/i, '');
  if (!SEMVER.test(normalized)) throw new Error(`Unusable release version: ${version}`);
  return normalized;
}

export function overlayAppImageAssetName(version: string): string {
  return `AquariusEditor-${normalizeOverlayVersion(version)}-x86_64.AppImage`;
}

export function overlayReleaseAssets(version: string): OverlayReleaseAssets {
  const normalized = normalizeOverlayVersion(version);
  const assetName = overlayAppImageAssetName(normalized);
  const base = `${RELEASE_DOWNLOAD_BASE}/v${normalized}`;
  return {
    assetName,
    appImageUrl: `${base}/${assetName}`,
    checksumsUrl: `${base}/${CHECKSUM_ASSET_NAME}`,
  };
}

/**
 * Parses a `sha256sum` manifest into name → digest.
 *
 * The release workflow runs `sha256sum ./*`, so names arrive as `./AquariusEditor-…`;
 * `sha256sum -b` would prefix the name with `*`. Both are normalised away.
 */
export function parseSha256Sums(text: string): Map<string, string> {
  const digests = new Map<string, string>();
  for (const line of text.split('\n')) {
    const match = line.trim().match(/^([0-9a-f]{64})\s+\*?(.+)$/i);
    if (!match) continue;
    const name = match[2]!.trim().replace(/^\.\//, '');
    if (name) digests.set(name, match[1]!.toLowerCase());
  }
  return digests;
}

export function expectedSha256(text: string, assetName: string): string | null {
  return parseSha256Sums(text).get(assetName) ?? null;
}

/**
 * Repoints `<overlayRoot>/current` at `versions/<version>` in one atomic step.
 *
 * A symlink cannot be edited in place, so the new one is created under a temporary name
 * and renamed over the old one: readers either see the old target or the new one, never
 * a missing `current`. The link is relative so the overlay stays movable.
 */
export async function swapOverlayCurrent(overlayRoot: string, version: string): Promise<void> {
  const normalized = normalizeOverlayVersion(version);
  const link = join(overlayRoot, CURRENT_LINK);
  const staged = join(overlayRoot, `.${CURRENT_LINK}.${process.pid}.${Date.now()}`);
  // rename() replaces a symlink or a file, but refuses to replace a directory.
  const existing = await lstat(link).catch(() => null);
  if (existing?.isDirectory()) await rm(link, { recursive: true, force: true });
  await rm(staged, { force: true });
  await symlink(join(VERSIONS_DIR, normalized), staged);
  try {
    await rename(staged, link);
  } catch (error) {
    await rm(staged, { force: true });
    throw error;
  }
}

/** The version `current` resolves to, or null when the link is missing or unreadable. */
export async function readOverlayCurrentVersion(overlayRoot: string): Promise<string | null> {
  const target = await readlink(join(overlayRoot, CURRENT_LINK)).catch(() => null);
  if (!target) return null;
  return target.split('/').filter(Boolean).pop() ?? null;
}

/**
 * Deletes every installed version except the one just installed (and, defensively, whatever
 * `current` actually points at). An extracted install is roughly 2.1 GB, so keeping old
 * copies around would fill a handheld's disk in three updates.
 */
export async function pruneOverlayVersions(overlayRoot: string, keepVersion: string): Promise<string[]> {
  const keep = new Set([normalizeOverlayVersion(keepVersion)]);
  const linked = await readOverlayCurrentVersion(overlayRoot);
  if (linked) keep.add(linked);
  const versionsDir = join(overlayRoot, VERSIONS_DIR);
  const entries = await readdir(versionsDir).catch(() => [] as string[]);
  const removed: string[] = [];
  for (const entry of entries) {
    if (keep.has(entry)) continue;
    await rm(join(versionsDir, entry), { recursive: true, force: true });
    removed.push(entry);
  }
  return removed.sort();
}

async function downloadToFile(
  url: string,
  destination: string,
  onProgress: (percent: number) => void,
): Promise<void> {
  const response = await fetch(url, { redirect: 'follow' });
  if (!response.ok || !response.body) {
    throw new Error(`Update download failed (${response.status}) for ${url}`);
  }
  const total = Number(response.headers.get('content-length') ?? 0);
  let received = 0;
  let reported = -1;
  const meter = new Transform({
    transform(chunk: Buffer, _encoding, callback) {
      received += chunk.length;
      if (total > 0) {
        const percent = Math.min(100, Math.round((received / total) * 100));
        // Only forward whole-percent changes; the renderer redraws on every state publish.
        if (percent !== reported) {
          reported = percent;
          onProgress(percent);
        }
      }
      callback(null, chunk);
    },
  });
  await pipeline(
    Readable.fromWeb(response.body as Parameters<typeof Readable.fromWeb>[0]),
    meter,
    createWriteStream(destination),
  );
}

async function fetchText(url: string): Promise<string> {
  const response = await fetch(url, { redirect: 'follow' });
  if (!response.ok) throw new Error(`Checksum download failed (${response.status}) for ${url}`);
  return response.text();
}

async function hashFile(path: string): Promise<string> {
  const hash = createHash('sha256');
  await pipeline(createReadStream(path), hash);
  return hash.digest('hex');
}

async function extractAppImage(appImagePath: string, workDir: string): Promise<void> {
  await new Promise<void>((resolve, reject) => {
    // Self-extraction is built into the AppImage runtime and needs no FUSE, which the
    // AquariusOS image does not guarantee for an unprivileged session.
    const child = spawn(appImagePath, ['--appimage-extract'], { cwd: workDir, stdio: 'ignore' });
    child.once('error', reject);
    child.once('close', (code) => {
      if (code === 0) resolve();
      else reject(new Error(`--appimage-extract exited with ${code}`));
    });
  });
}

export const defaultOverlayUpdateIo: OverlayUpdateIo = {
  downloadFile: downloadToFile,
  fetchText,
  hashFile,
  extractAppImage,
};

/**
 * Downloads, verifies, extracts, and activates `version` under `overlayRoot`.
 *
 * Resolves with the installed directory. On any failure the partial work is deleted and
 * `current` still points wherever it pointed before, so the running install stays intact.
 */
export async function installOverlayUpdate(
  overlayRoot: string,
  version: string,
  hooks: OverlayInstallHooks = {},
  io: OverlayUpdateIo = defaultOverlayUpdateIo,
): Promise<string> {
  const normalized = normalizeOverlayVersion(version);
  const assets = overlayReleaseAssets(normalized);
  const versionsDir = join(overlayRoot, VERSIONS_DIR);
  await mkdir(versionsDir, { recursive: true });
  await mkdir(join(overlayRoot, WORK_DIR), { recursive: true });
  // The work directory lives inside the overlay so the extracted tree can be moved into
  // place with a rename() instead of a second 2 GB copy across filesystems.
  const workDir = await mkdtemp(join(overlayRoot, WORK_DIR, 'install-'));
  const installedDir = join(versionsDir, normalized);
  let claimedInstalledDir = false;

  try {
    const appImagePath = join(workDir, assets.assetName);
    await io.downloadFile(assets.appImageUrl, appImagePath, (percent) => {
      hooks.onProgress?.(percent);
    });

    const expected = expectedSha256(await io.fetchText(assets.checksumsUrl), assets.assetName);
    if (!expected) {
      throw new Error(`${assets.assetName} is not listed in ${CHECKSUM_ASSET_NAME}`);
    }
    const actual = (await io.hashFile(appImagePath)).toLowerCase();
    if (actual !== expected) {
      throw new Error(`${assets.assetName} failed its SHA-256 check (expected ${expected}, got ${actual})`);
    }

    hooks.onExtractStart?.();
    await chmod(appImagePath, 0o755);
    await io.extractAppImage(appImagePath, workDir);
    const extracted = join(workDir, EXTRACTED_DIR);
    const extractedStat = await stat(extracted).catch(() => null);
    if (!extractedStat?.isDirectory()) {
      throw new Error(`--appimage-extract produced no ${EXTRACTED_DIR} directory`);
    }

    await rm(installedDir, { recursive: true, force: true });
    claimedInstalledDir = true;
    await rename(extracted, installedDir);
    await swapOverlayCurrent(overlayRoot, normalized);
    await pruneOverlayVersions(overlayRoot, normalized);
    return installedDir;
  } catch (error) {
    if (claimedInstalledDir) await rm(installedDir, { recursive: true, force: true }).catch(() => undefined);
    throw error;
  } finally {
    await rm(workDir, { recursive: true, force: true }).catch(() => undefined);
  }
}

export function createOverlayUpdateInstaller(
  overlayRoot: string,
  io: OverlayUpdateIo = defaultOverlayUpdateIo,
): OverlayUpdateInstaller {
  return {
    overlayRoot,
    install: (version, hooks) => installOverlayUpdate(overlayRoot, version, hooks, io),
  };
}
